name = "EncarDida"
uuid = "02e349df-1276-4b7c-8caf-81d940f53876"
authors = ["Abel Soares Siqueira <abel.s.siqueira@gmail.com>", "Lucas Pedroso", "Rog√©rio Mainardes", "Rafaela Pereira"]
version = "0.1.0"
